### ISSUE TITLE
CISAZ32 - Memory Leak causes crash on having too many StorageAccount Keys with enormous size [BUG]

### ISSUE THREAD

**Issue by HanVer471** [CompliantSec/M365SAT#53] opened 2024-09-12 09:58 UTC
Hi, 
when I run the tool at a stage memory builds up (up to 26 gb). systems starts swapping and finally the computers crashes and restarts.
Check printscreen in attachment.
I have run on several systems now, problem persists.  Can you provide any advice or feedback?
![get-azstorageblob](https://github.com/user-attachments/assets/98ab3b0c-a60c-443a-876d-d0d421d9611f)

**Comment by asterictnl-lvdw** [comment] 2024-09-12 12:21
Hi @HanVer471 ,

Kindly provide me the following:
- What command are you using?
- Which version of M365SAT are you using?
- At which Inspector you get the memory leak? 
- Have you tried the same command separately to see if it is an issue based on the Az module? 

I want to verify if its an issue with my inspector causing a memory leak. Because if there is an issue with the command you should raise this issue at the AzPowerShell github here: https://github.com/Azure/azure-powershell/issues

I will look forward to your information.

~LvdW

**Comment by HanVer471** [comment] 2024-09-13 12:08
Hello ,

See below

Vriendelijke groeten,


From: Leonardo van de Weteringh ***@***.***>
Sent: donderdag 12 september 2024 14:22
To: asterictnl-lvdw/M365SAT ***@***.***>

Subject: Re: [asterictnl-lvdw/M365SAT] Crash on get-azstorageblob (Issue #53)


Hi @HanVer471<https://github.com/HanVer471> ,

Kindly provide me the following:

  *   What command are you using?
                Get-M365SATReport -OutPath "C:\M365SAT-alpha\Out" -Username ***@***.******@***.***> -EnvironmentType AZURE -BenchmarkVersion "Latest" -Modules "All" -LicenseMode "All" -LicenseLevel "All" -reportType "HTML" -AllowLogging "warning" -LocalMode -SkipChecks

  *   Which version of M365SAT are you using?
2.3 Alpha, but have the same issue with 2.2 production

  *   At which Inspector you get the memory leak?
It fails at CISaz32

  *   Have you tried the same command separately to see if it is an issue based on the Az module?
I ran CISaz32.ps1 seperately and the memory leak occurred again

I want to verify if its an issue with my inspector causing a memory leak. Because if there is an issue with the command you should raise this issue at the AzPowerShell github here: https://github.com/Azure/azure-powershell/issues

I will look forward to your information.

~LvdW

**Comment by asterictnl-lvdw** [comment] 2024-09-16 08:16
Hi @HanVer471 ,

I have checked the command onto my test-environment and other environment, and it does not result into having a memory leak. We have to find out why it is causing a memory leak in the first place. I think it is because of the amount of blobs you have in some containers, but I am not sure, because I do not know your environment. :)

According to a posted issue I can see the Az Blob and Storage commands have some problems when handling large sized blobs: https://github.com/Azure/azure-powershell/issues/23787

To verify some thing I need more information:
- What Az version are you using?

Run the following commands:
`(Get-AzStorageAccount).Count`

How many StorageAccounts are you trying to audit?

I have provided a possible workaround
```
	try
	{
		$violation = @()
		$StorageAccounts = Get-AzStorageAccount -ErrorAction SilentlyContinue | Select-Object StorageAccountName,ResourceGroupName 
		foreach ($StorageAccount in $StorageAccounts){
			try{
				$StorageAccountKey = (Get-AzStorageAccountKey -ResourceGroupName $StorageAccount.ResourceGroupName -Name $StorageAccount.StorageAccountName -ErrorAction SilentlyContinue -WarningAction SilentlyContinue).Value[0] 
				$AzStorageContext = New-AzStorageContext -StorageAccountName $StorageAccount.StorageAccountName -StorageAccountKey $StorageAccountKey -ErrorAction SilentlyContinue -WarningAction SilentlyContinue
				$Containers = Get-AzStorageContainer -Context $AzStorageContext -ErrorAction SilentlyContinue -WarningAction SilentlyContinue
				ForEach ($Container in $Containers){
					[Diagnostics.Trace]::Listeners.Clear()
					$Blobs = Get-AzStorageBlob -Container $Container.Name -Context $AzStorageContext -WarningAction SilentlyContinue
					ForEach ($Blob in $Blobs){
						$Check = $Blob | Select-Object -ExpandProperty ICloudBlob | Select-Object -ExpandProperty Properties | Select-Object IsServerEncrypted
						if ($Check.IsServerEncrypted -eq $False){
							$violation += $Blob.Name
						}
					}
					[Diagnostics.Trace]::Listeners.Clear()
				}
				
			}
			catch
			{
				continue
			}
		}
```

Please kindly check if that command is working and not resulting into a memory leak and outofmemory exception.

Thank you.

~LvdW

**Comment by asterictnl-lvdw** [comment] 2024-09-27 08:59
@HanVer471 ,

Please kindly let me know if this fixes the issue so I can implement it into the next release.

~LvdW

**Comment by HanVer471** [comment] 2024-09-27 14:24
Hello,

The environment counts 56 storage accounts and contains around 180 containers and/or file shares in total.
This one worked, with export to CSV


From: Leonardo van de Weteringh ***@***.***>
Sent: vrijdag 27 september 2024 11:00
To: asterictnl-lvdw/M365SAT ***@***.***>

Subject: Re: [asterictnl-lvdw/M365SAT] Crash on get-azstorageblob (Issue #53)


@HanVer471<https://github.com/HanVer471> ,

Please kindly let me know if this fixes the issue so I can implement it into the next release.

~LvdW

**Comment by asterictnl-lvdw** [comment] 2024-09-30 07:08
That's great to hear! I will implement this fix into the inspector on the next quick release.

Thank you very much and I will close this issue.

~LvdW

**Closed as completed by asterictnl-lvdw** 2024-09-30 07:08 UTC
Labels: bug

**Comment by milope** [comment] 2025-01-29 21:31
FYI, I was the person that reported the `Get-AzStorageBlob` issue, and it's related more to actually iterating over and over, rather than single blob sizes. The issue could reproduce with small blobs as well. I was testing a scenario where I was recovering 1.5 million soft-deleted blobs and saw the memory leak. All my blobs were a few bytes in size.
