### ISSUE TITLE
Narrow down needed modules

### ISSUE THREAD

**Issue by M-gre** [CompliantSec/M365SAT#34] opened 2024-04-23 13:48 UTC
Hi
I tried to narrow down the actually needed modules to run the assessment tool. Since the Az and Graph Modules include a large amount of submodules, the install can take a while even though not all submodules are strictly required. I tried to identify every needed module using the AST of all scripts, which resulted in these:

```Az.Accounts
Az.ApplicationInsights
Az.Compute
Az.CosmosDB
Az.KeyVault
Az.Monitor
Az.MySql
Az.Network
Az.OperationalInsights
Az.PostgreSql
Az.Resources
Az.Security
Az.Sql
Az.Storage
Az.Websites

ExchangeOnlineManagement

Microsoft.Graph.Applications
Microsoft.Graph.Authentication
Microsoft.Graph.DirectoryObjects
Microsoft.Graph.Groups
Microsoft.Graph.Identity.SignIns
Microsoft.Graph.Identity.DirectoryManagement
Microsoft.Graph.Security
Microsoft.Graph.Users

Microsoft.Graph.Beta.Identity.SignIns

Microsoft.Online.SharePoint.PowerShell

MicrosoftTeams

PoShLog
```

Obviously this list will change as different tests get added but I believe keeping the modules down to a minimum would be a good idea.

**Comment by asterictnl-lvdw** [comment] 2024-04-23 13:52
Hello,

Thank you for your submission

Could you test this out in the next release for me which modules are required? Then I can add them to the list. I am planning to release that somewhere in May hopefully if things are working out.

Thank you. :)

~LvdW

**Comment by M-gre** [comment] 2024-04-23 13:59
Yes, that would not be an issue. I will try it out in the next release

**Comment by asterictnl-lvdw** [comment] 2024-05-06 09:31
I will release the Production version today. If you have time to test it out for me which modules are required i'll change them in v2.3 and release that, :)

~LvdW

**Comment by M-gre** [comment] 2024-05-06 18:36
Hi, yes I will test it tomorrow or the day after that and will let you know
then.

**Comment by asterictnl-lvdw** [comment] 2024-05-07 07:40
It has been released so feel free to test it out when you are ready <3

**Comment by M-gre** [comment] 2024-05-07 12:24
It seems that the needed modules have stayed the same, so the install instructions could be narrowed down to the list I reported initially. For the test I looked at the source of all functions that are used anywhere in the code (Get-Command). To be very sure I would need to now test the reverse, where I do a clean setup and only install the mentioned modules and see what happens.

In the analysis I also saw, that quite a few tests still rely on Exchange-Powershell commands (e.g. Get-Mailbox). I would assume that there would be issues using these commands, since the modules are no longer supported? I can get you a list of all commands that I found, should I open a separate issue for this or is this known?

**Comment by asterictnl-lvdw** [comment] 2024-05-07 15:20
Hi,

First of all, thank you for looking at it! :)

Do test it out for me with only those modules to see if there will be no issues. Then I will push those things to next release. For Microsoft Graph it will not be an issue, but for the Az Module I need to look if I can install them separately as that is a whole package you install, and it has some dependencies

I use Get-Mailbox for ExchangeOnlineManagement and not EXO modules yet, because I have run into issues with the EXO Mailbox in some commands that it was not working and breaking a lot of modules, most likely some timeout issues. And I couldn't reproduce them unfortunately outside of the environment. 

As long there are these issues with EXO, I will be careful with updating that part of the scripts. It might be also because of the IPPS Session Connection migration Microsoft made which is now REST-API based as well.

If you can find out also the Connect-Graph to see which permissions need to be assigned, that would be great then I can narrow that down as well as the Graph app will not have too many consents applied onto the account that is used respectively to login and to the authentication.

If you can get me the list of commands, then I will look at those and put them on the list to rewrite them and also push them to alpha. You can post them into a different issue, that is the best, because those things are not related to this issue. :)

Thank you again and I will look forward analyzing the issue and implementing the enhancement for you.

~LvdW

**Comment by M-gre** [comment] 2024-05-08 06:42
Thanks for the information. My tests with just the modules installed where not that successfull. It is hard to exactly pin it down, since my test tenant setup is not really ideal. I currently don't have a azure subscription attached and will get a lot of error messages for the azure connections.
I will try around some more and also change the setup. I will also try to install the Az package as a whole. I was trying to break that package down if possible since it is so large.

I had some success in the past with finding the needed Graph scope using the [Find-MgGraphPermission](https://learn.microsoft.com/en-us/powershell/microsoftgraph/find-mg-graph-permission?view=graph-powershell-1.0&WT.mc_id=M365-MVP-9501) command.

**Comment by asterictnl-lvdw** [comment] 2024-05-08 07:32
I was already afraid of that breaking down the modules would cause issues. 

I do recommend you testing it with an azure subscription as well since then you can see if there will be errors and such. If you do not have an azure subscription, you can use the new parameters to only scan on Microsoft 365 environment instead of Azure as well. Microsoft 365 environment should only have Entra ID things and no other things that would require an azure subscription as additional resources need to be created for that.

I will look forward to your findings.

~LvdW

**Comment by M-gre** [comment] 2024-05-08 12:03
I've tried it out with the whole Az and Graph modules installed and still seem to get the same errors. I'm now not quite sure on how to best go forward, since I can't pin it down at the moment what the actual underlying issue is.

For example this is one of the error messages that I get after starting the assessment:
``` 
Get-MgDirectoryRole : Method not found: 'Void Microsoft.Graph.Authentication.AzureIdentityAccessTokenProvider..ctor(Azure.Core.TokenCredential, System.String[], 
Microsoft.Kiota.Authentication.Azure.ObservabilityOptions, System.String[])'.
At C:\Users\WDAGUtilityAccount\Downloads\M365SAT-production\inspectors\M365\Azure\CIS30\E3\L1\CISMAz113.ps1:45 char:3
+         $globalAdminRole = Get-MgDirectoryRole -Filter "RoleTemplateI ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Get-MgDirectoryRole_List], MissingMethodException
    + FullyQualifiedErrorId : Microsoft.Graph.PowerShell.Cmdlets.GetMgDirectoryRole_List 
```
After this it seems that the error are cascading, since some neccessary infos can't be read from the tenant. I tried looking online for this error message, but could not get it to work from what I found. I will try further, but it will take a bit more time.

**Comment by asterictnl-lvdw** [comment] 2024-05-08 15:10
@M-gre 

Thank you for sharing. It seems that the module wasn't deleted before the new release. This has been cooked into the new CISMOff113 now which has the correct script. You can delete that .ps1 script as that one has been replaced by a different one. :)

Do test it out once again and let me know if you stumble upon weird errors. :)

~LvdW

**Comment by M-gre** [comment] 2024-05-14 08:01
Hi, sorry for the late response. I found mostly three types of errors. 
The first is in regards to the Exchange modules, where the commands are not recognized. Here an example:
```
[04:59:59 ERR] An error occured on line 43 char 21 : 		$TransportRules = Get-TransportRule | Where-Object { $_.Redirec
tMessageTo -ne $null } | Format-Table Name, RedirectMessageTo

System.Management.Automation.CommandNotFoundException: The term 'Get-TransportRule' is not recognized as the name of a
 cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify
 that the path is correct and try again.
   at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception e
xception)
   at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
````

The second and third are for the Sharepoint and Teams inspectors, where the there are problems with the authentication. The commands can't be run, because the Connect-SPOService and Connect-MicrosoftTeams are not established:
```
[05:00:05 WRN] The Inspector: C:\Users\User\Downloads\M365SAT-production\inspectors\M365\Sharepoint\CIS30\E3\L2\CISMSp
732.ps1 was terminated!
[05:00:05 ERR] An error occured on line 43 char 21 : 		$ShareSettings = (Get-SPOTenant).ConditionalAccessPolicy

System.InvalidOperationException: No connection available. Use Connect-SPOService before running this CmdLet.
   at Microsoft.Online.SharePoint.PowerShell.BaseSPOCmdlet.get_Context()
   at Microsoft.Online.SharePoint.PowerShell.GetSPOTenant.Execute()
   at System.Management.Automation.CommandProcessor.ProcessRecord()
```

```
[05:00:11 WRN] The Inspector: C:\Users\User\Downloads\M365SAT-production\inspectors\M365\Teams\CIS30\E3\L1\CISMTm812.p
s1 was terminated!
[05:00:11 ERR] An error occured on line 42 char 3 : 		$MicrosoftTeamsCheck = Get-CsTeamsClientConfiguration -Identity 
Global | Select-Object AllowEmailIntoChannel

System.UnauthorizedAccessException: Session is not established, run Connect-MicrosoftTeams before requesting access to
ken
   at Microsoft.Teams.ConfigApi.Cmdlets.CmdletHostWrapper.GetAccessToken(String appId, String scope)
   at Microsoft.Teams.ConfigApi.Cmdlets.SessionStateStore.GetLoginInfo()
   at Microsoft.Teams.ConfigApi.Cmdlets.SessionStateStore.GetSessionState()
   at Microsoft.Teams.ConfigApi.Cmdlets.FlightingUtils.GetFlightingCommandInfo(Dictionary`2 boundParameters, String re
motingCommand, OverrideFlightMode overrideFlight)
   at Microsoft.Teams.ConfigApi.Cmdlets.TrpsPSCmdlet.TryGetFlightedApi(FlightingCommandInfo& flightedCommand, List`1 p
ipelineInputKeys)
   at Microsoft.Teams.ConfigApi.Cmdlets.TrpsPSCmdlet.ProcessRecord()
   at System.Management.Automation.CommandProcessor.ProcessRecord()
```

**Comment by asterictnl-lvdw** [comment] 2024-05-14 08:30
@M-gre 

Please share the command you are trying to use in M365SAT-Tester or the command you are executing. Are you getting errors already in the first process when trying to connect to the modules? Also are you using PowerShell 7 or are you using the built-in Powershell 5.1?

The 2nd one happens when you did not successfully establish a connection with the SPO-Module and the same with the 3rd one.

The way of connecting to all modules has been done in a way to make sure all modules are working properly. If you change around the order of connecting to modules you will stumble upon errors and things not working. It happens if you connect to all modules you have to do it in this order:
1. Connect-AzAccount
2. Connect-Graph
3. Connect-ExchangeOnline
4. Connect-IPPSSession
5. Connect-SPOService
6. Connect-MicrosoftTeams

The process itself seems to be a bit sluggish sometimes. I really wish I can optimize it where possible, but it happens that it generates a lot of errors when you connect something before something as there are dependencies.

~LvdW

**Comment by M-gre** [comment] 2024-05-14 09:31
Sorry forgot to mention what I actually did for the testing. This is using Powershell 5.1 from a fresh VM where I installed the needed modules and the project. I only used the M365SATTester script, where my run command is as follows `Get-M365SATReport -OutPath "C:\Out" -Username "admin@tenant" -EnvironmentType M365 -BenchmarkVersion "Latest" -Modules "All" -LicenseMode "E3" -LicenseLevel "All" -reportType "HTML" -AllowLogging "Warning" -LocalMode -SkipChecks`. Therefore the order of connecting to the modules should be correct. 

When I run the command I get two authentication requests, if I recall correctly. One in the browser and one in the embedded login screen. I could try to open the sessions first, before running the tester script, or would this cause other issues?

The logs for the start of the script are as following:
```
[04:59:54 WRN] Program Started!
05/10/2024 04:59:54: Checking Existence SkipChecks Parameter...
05/10/2024 04:59:54: Initiating Connections...
Connecting to Microsoft Azure Powershell...
Connected to Microsoft Azure Powershell!
Connecting to Microsoft Graph Powershell...
Connected to Microsoft Graph Powershell!
Get-MgOrganization : Method not found: 'Void 
Microsoft.Graph.Authentication.AzureIdentityAccessTokenProvider..ctor(Azure.Core.TokenCredential, System.String[], 
Microsoft.Kiota.Authentication.Azure.ObservabilityOptions, System.String[])'.
At C:\Users\User\Downloads\M365SAT-production\core\m365connectors\Connect-MicrosoftGraph.ps1:27 char:3
+         $OrgName = (((Get-MgOrganization).VerifiedDomains |  Where-Ob ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Get-MgOrganization_List], MissingMethodException
    + FullyQualifiedErrorId : Microsoft.Graph.PowerShell.Cmdlets.GetMgOrganization_List
 
05/10/2024 04:59:55: Getting Inspectors...
05/10/2024 04:59:55: Executing Inspectors in SingleThread Mode...
```
I can't see any connection requests for other modules.

**Comment by M-gre** [comment] 2024-05-14 09:35
Also just tried out all the connection commands you listed on their own. I could connect to all services by themselves just fine.

**Comment by asterictnl-lvdw** [comment] 2024-05-14 09:38
@M-gre ,

Ah, I see it here. It breaks once it raises an exception and goes straight to the inspectors. That should not be happening. I will make a failover validation to make sure the script will exit if such error occurs. 

Can you verify the following:

- Do you have the Microsoft.Graph (normal) module installed?
- Do you have the Microsoft.Graph.Beta module installed?
- When connecting to graph. Could you run `Get-MgOrganization` to check if you actually get something back? It seems that it could not execute Get-MgOrganization as it might be part either of a module in Microsoft.Graph(.Beta) or that something has gone wrong.

Can you also verify what happens if you fully install Microsoft Graph and the Beta modules fully with the script in the README.md? I want to see if it is a configuration issue or something else.

Thank you.

~LvdW

**Comment by M-gre** [comment] 2024-05-14 09:47
At the moment for the testing I have only installed the reduced modules for both Graph normal and beta. When I run `Get-MgOrganization` I get the error that was also seen in the log:
```
Get-MgOrganization : Method not found: 'Void 
Microsoft.Graph.Authentication.AzureIdentityAccessTokenProvider..ctor(Azure.Core.TokenCredential, System.String[], 
Microsoft.Kiota.Authentication.Azure.ObservabilityOptions, System.String[])'.
At line:1 char:1
+ Get-MgOrganization
+ ~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Get-MgOrganization_List], MissingMethodException
    + FullyQualifiedErrorId : Microsoft.Graph.PowerShell.Cmdlets.GetMgOrganization_List
```
From what I could see the command [should be a part of the Graph.Identity.DirectoryManagement module](https://learn.microsoft.com/en-us/powershell/module/microsoft.graph.identity.directorymanagement/get-mgorganization?view=graph-powershell-1.0) that is installed.

I will try try out reinstalling the specific module and if that doesn't fix it, the general module (first normal, then beta).

**Comment by M-gre** [comment] 2024-05-14 10:00
Okay, so reinstalling the specific module (DirectoryManagement) with -Force allowed me to get a correct response from `Get-MgOrganization`. But if I then run the Tester script I still get errors for the same thing:
```
[11:55:22 WRN] Program Started!
05/14/2024 11:55:22: Checking Existence SkipChecks Parameter...
05/14/2024 11:55:22: Initiating Connections...
Connecting to Microsoft Azure Powershell...
Connected to Microsoft Azure Powershell!
Connecting to Microsoft Graph Powershell...
Connected to Microsoft Graph Powershell!
Get-MgOrganization : Method not found: 'Void 
Microsoft.Graph.Authentication.AzureIdentityAccessTokenProvider..ctor(Azure.Core.TokenCredential, System.String[], 
Microsoft.Kiota.Authentication.Azure.ObservabilityOptions, System.String[])'.
At C:\Users\User\Downloads\M365SAT-production\core\m365connectors\Connect-MicrosoftGraph.ps1:27 char:3
+         $OrgName = (((Get-MgOrganization).VerifiedDomains |  Where-Ob ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Get-MgOrganization_List], MissingMethodException
    + FullyQualifiedErrorId : Microsoft.Graph.PowerShell.Cmdlets.GetMgOrganization_List
 
05/14/2024 11:55:47: Getting Inspectors...
```
I also get the same error if I try to run `Get-MgOrganization` right after starting and quitting the Tester script. If I close the PS session and restart a new one I can run it just fine again.

**Comment by asterictnl-lvdw** [comment] 2024-05-14 10:28
@M-gre ,

I unfortunately cannot reproduce the issue, but I do know that this error is based on the Microsoft.Graph(.Beta) module.

When you are trying to run the M365SAT-Tester make sure you are NOT connected to any of the modules yet, connecting to them in advance will cause issues with the process and makes you unable to execute the audit properly. 

Try to close all PowerShell windows and open one as admin and execute the M365SATTester. Then test afterwards if the script works again. Because it seems that Microsoft Graph does not get connected correctly and that there is still a dependency somewhere in the process. 

As mentioned, try remove the Microsoft Graph modules and reinstall them by running these two commands:
```
# Microsoft Graph
Install-Module Microsoft.Graph -AllowClobber -Force
# For Microsoft Graph beta
Install-Module Microsoft.Graph.Beta -AllowClobber -Force
```
This was mentioned in an early version of Microsoft Graph as it causes issues when you do not use the AllowClobber to install them alongside.
https://github.com/microsoftgraph/msgraph-sdk-powershell/releases/

Please let me know if that works for you. I will change it in the README.md as well and add for the Microsoft Graph modules the -AllowClobber -Force parameters to make them work properly
Thank you.

~LvdW

**Comment by M-gre** [comment] 2024-05-27 13:41
Hi, I wasn't able to test this out until now.
`AllowClobber` was the thing that was missing. I can run the M365SATTester without issues now. Next step would be to try this option with the individual modules once again. I will let you know what I find out, but it may take some time again for me to come around to more tests. Thank you for the support in getting the script running :)

**Comment by M-gre** [comment] 2024-06-10 14:31
Hi, I haven't found the time to try the script with the individual modules, but was able to try the script in a different tenant and everything worked perfectly :) What I did try out was to narrow down the Graph scopes using [this PS module](https://doitpshway.com/how-to-get-all-graph-api-permissions-required-to-run-selected-code-using-powershell).

Here are all the read scope that the module was able to find in the calls from the inspectors:  
> Directory.Read.All
RoleManagement.Read.Directory
DeviceManagementServiceConfig.Read.All
DeviceManagementConfiguration.Read.All
User.Read.All
Policy.Read.All
DeviceManagementManagedDevices.Read.All
DeviceManagementApps.Read.All
Group.Read.All
UserAuthenticationMethod.Read.All
GroupMember.Read.All
Organization.Read.All
Domain.Read.All
Policy.Read.DeviceConfiguration
AccessReview.Read.All
SecurityEvents.Read.All
Application.Read.All

I can't guarantee that this is a comprehensive list, but I hope this still helps :)

**Comment by asterictnl-lvdw** [comment] 2024-06-10 14:34
This is already great! I will test this with the next upcoming release so see if ever module is working with the new benchmark.

If everything is in order I will push the new release to alpha so it can be tested.

~LvdW

**Comment by asterictnl-lvdw** [comment] 2024-06-13 12:04
I have implemented the Microsoft.Graph change if you still can find which Graph modules we do not need. Then I can check if that does impact. I think the best thing is that the permissions already are broken down. Eventually I might have to add extra permissions in case new things come in the next benchmark version.

You can test it by cloning the Alpha branch: https://github.com/asterictnl-lvdw/M365SAT/tree/alpha

~LvdW

**Comment by asterictnl-lvdw** [comment] 2024-07-26 09:27
Hello @M-gre ,

Once I have pushed the update to master please test it again, if everything is OK I will close this issue. 

~LvdW

**Comment by asterictnl-lvdw** [comment] 2024-08-14 10:13
I have tested it on Alpha and pushed it towards Master. It works as expected. This issue has been resolved and is now closed.

~LvdW

**Closed as completed by asterictnl-lvdw** 2024-08-14 10:13 UTC
Labels: enhancement
