### ISSUE TITLE
Objects were sorted duplicated on multiple findings within the HTML report

### ISSUE THREAD

**Issue by frisotrip** [CompliantSec/M365SAT#47] opened 2024-08-22 10:19 UTC
Hello

Testing this script now.
After a while i got an html result with a lot of info.
Problem is that when i expand lets say teams or exchange, the output is the same everywhere.
Also the question if the script runs on users with Business premium or other licenses as E....?

Thanx 
Friso

**Comment by asterictnl-lvdw** [comment] 2024-08-22 12:06
Hello Friso,

Thank you for your submission.

Please provide me the following:
- Which version are you using
- What command are you using?
- Are you using the M365SATTester.ps1 to execute this?
- If you are allowed, please share a screenshot, removing sensitive info regarding the information.
- Did you use Windows PowerShell or PowerShell 5.1?

Please provide me the information so I can reproduce the issue if existing.

Thanks in advance.

~Leonardo

P.S.: Please read the Code of Conduct next time before submitting an issue: https://github.com/asterictnl-lvdw/M365SAT/blob/production/CODE_OF_CONDUCT.md

Thank you.

**Comment by frisotrip** [comment] 2024-08-22 12:54
Leonardo

I am using v2.3 i think it is the latest version. Iam indeed using the command M365SATTester.ps1.
Find attached some screenshots
And also using powershell 7.

![03 2024-08-22 14_50_08-Windows 11 M365 Security check - VMware Workstation](https://github.com/user-attachments/assets/7ab85ea2-8689-4e5b-a89d-8083f0768f9e)
![02 2024-08-22 14_49_06-Windows 11 M365 Security check - VMware Workstation](https://github.com/user-attachments/assets/1611d118-ca8a-4d9f-a15b-2f859e473a41)
![01 2024-08-22 14_47_36-Windows 11 M365 Security check - VMware Workstation](https://github.com/user-attachments/assets/5501d823-1635-4b46-99b4-a2585f31aa8f)

**Comment by asterictnl-lvdw** [comment] 2024-08-22 13:19
@frisotrip ,

I see it indeed! 

Can you go to the `Get-M365SATHTMLReport.ps1`. On line 689 there is this piece of code:
`$Products = $(foreach ($Product in $object.Findings) { $Product | ? { $_.ProductFamily -eq $Productfamily } }) | Sort-Object -Descending { Switch -Regex ($_.RiskRating) { 'Critical' { 1 }	'High' { 2 } 'Medium' { 3 }	'Low' { 4 }	'Informational' { 5 } }; $_.RiskScore},$_.ID`

Please remove the `,$_.ID` from it and let me know if the objects are returned properly.

Thank you.

~LvdW

**Comment by frisotrip** [comment] 2024-08-22 13:48
Leonardo

That did the trick
No wit looks much better.
Thanx for the quick fix.

**Comment by asterictnl-lvdw** [comment] 2024-08-22 14:30
No worries. This was due to an update. I will look into this object sorting issue and see if I can sort it correctly. The problem was that once it was sorted the ID's weren't sorted resulting into having issues randomly putted into the array. 

I will push this to release as a quick fix, no need to change the version number for it. I will close this issue for now.

~Leonardo

**Closed as completed by asterictnl-lvdw** 2024-08-22 14:30 UTC
Labels: bug
